//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DI.Reminder.Data.AdvertisingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvertisingService.IAdvertising")]
    public interface IAdvertising {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvertising/GetItems", ReplyAction="http://tempuri.org/IAdvertising/GetItemsResponse")]
        DI.Reminder.Service.DataContract.AdvertisingItem[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvertising/GetItems", ReplyAction="http://tempuri.org/IAdvertising/GetItemsResponse")]
        System.Threading.Tasks.Task<DI.Reminder.Service.DataContract.AdvertisingItem[]> GetItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvertisingChannel : DI.Reminder.Data.AdvertisingService.IAdvertising, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvertisingClient : System.ServiceModel.ClientBase<DI.Reminder.Data.AdvertisingService.IAdvertising>, DI.Reminder.Data.AdvertisingService.IAdvertising {
        
        public AdvertisingClient() {
        }
        
        public AdvertisingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvertisingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertisingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertisingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DI.Reminder.Service.DataContract.AdvertisingItem[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<DI.Reminder.Service.DataContract.AdvertisingItem[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
    }
}
